# Parameters
WIDTH, HEIGHT = 800, 400
OBS_SIZE, FONT_SIZE = 40, 40  # for obstacles and font size
PLAYER_SIZE  = 50
CHAR_DEAD_SIZE = 80
COIN_SIZE = 30
ALTERNATE_ENEMY_SIZE = OBS_SIZE * 1.5
FINAL_BOSS_SIZE = ALTERNATE_ENEMY_SIZE * 1.5

SKY_LEVEL    = 150
GROUND_LEVEL = 333
FONT_POS_X   = 700
INIT_GRAVITY = -20
PLAYER_GROUND_LEVEL = (GROUND_LEVEL + 3/4 * PLAYER_SIZE)
